### ISSUE TITLE
Something wrong with the head file, unable to pass compilation.

### ISSUE THREAD

**Issue by saeziae** [DFRobot/DFRobot_SIM808#10]
```
DFRobot_sim808.h:55: error: expected `)' before '*' token
DFRobot_sim808.h:345: error: ISO C++ forbids declaration of 'SoftwareSerial' with no type
DFRobot_sim808.h:345: error: expected ';' before '*' token

```

**Comment by cnlg** [comment]
Your Arduino IDE did not detect your SoftwareSerial.h file, using another version of the Arduino IDE test.

**Comment by dmnc-net** [comment]
Don't use SoftwareSerial, use AltSoftSerial or NeoSWSerial instead. [Here](https://arduino.stackexchange.com/a/34130/6220) you can read the reason why.
