### ISSUE TITLE
Every http request after the first fails

### ISSUE THREAD

**Issue by busternr** [DFRobot/DFRobot_SIM808#12]
So i am using SIM808 Module with Arduino Mega 2560.The problem is that every time the first POST or GET http request to my server is always successful, but all of the requests after the first one cannot be made.I am getting the fetch over... message.I am following the TCPConnection example.

**Comment by danielkp1234** [comment]
@busternr Did you fix it im trying for mine to do a get request for submitting the long and latitude do you by any chance have that kind of code
