### ISSUE TITLE
warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

### ISSUE THREAD

**Issue by Ehtesham1558** [DFRobot/DFRobot_SIM808#26]
when i write my number in #define phone "xxxx" it is showing this error

**Comment by Skovie** [comment]
im getting that as well and I didn't even edit my number?
![Skærmbillede 2022-05-09 kl  23 00 18](https://user-images.githubusercontent.com/5016145/167497770-943fe04c-6fbe-4c31-96d4-bde5181a477d.png)

**Comment by qsjhyy** [comment]
(char*) forced conversion
